### PR TITLE
added overlay and onclick event to map so that it doesn't automatically scroll

### PR DESCRIPTION
**Pull request by nir0s**

### CODE REVIEW

**Comment by m1keil** [comment]
Breaks layout (Map covering "ORGANIZING COMMITTEE")
screenshot_2015-05-30-16-51-20

**Comment by nir0s** [comment]
damn... didn't check the phone. hmm, i'll try and fix.

**Comment by dzautner** [comment]
Not so sure about this solution. I did it myself at first but had to change it back. Pre-click the zoom buttons remain covered by the transparent div, rendering them inactive on the first click, and after the first click the map returns to it's old scroll-able state, so not much is gained from it.

**Comment by m1keil** [comment]
This mainly reduce the annoying experience one get while scrolling on small
screens.
I'm ok with the map returning to the old behavior after being clicked,
since the map is not the main point of the site.

**Comment by dzautner** [comment]
But it renders the zoom buttons unclickable until the map is clicked, that's not an acceptable behavior IMO

**Comment by m1keil** [comment]
In my tests, non of the buttons are clickable before the first click.

I guess it's a matter of preference. Both behaviors are not ideal,
personally as a user I prefer the second option (click to catch mouse).
Need more opinions here.

**Pull request closed without merging**
